### ISSUE TITLE
TypeError: console.Console is not a constructor

### ISSUE THREAD

**Issue by RALMAZ** [superhero/js.telnet#3]
![image](https://user-images.githubusercontent.com/26162860/105029992-c6df9f80-5a5b-11eb-8d36-d7971345b104.png)

**Comment by superhero** [comment]
What version of nodejs are you using?

**Comment by RALMAZ** [comment]
@superhero nvm fixed, I think was my mistake

**Comment by superhero** [comment]
I updated version of the Debugger as well to make sure, new version published just now: 1.2.1
